language: cpp
os: linux
compiler:
  - clang
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial-8
    packages: 
      - g++-9
      - clang-8
      - lcov

script: 
  - ./build.sh
  - cd ${TRAVIS_BUILD_DIR}  

after_success:
  # Creating coverage report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --version
  - lcov --capture --directory . --output-file coverage.info
  - lcov --remove coverage.info '/usr/*' "${HOME}" --output-file coverage.info # filter system-files
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

