dist: xenial
sudo: false
language: cpp
compiler:
  - clang
  - gcc

script:
  - cmake . -D ENABLE_COVERAGE:BOOL=TRUE
  - cmake --build . -- -j2
  - ctest -j2

after_success:
- bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  
