language: cpp
os: linux
dist: xenial

branches:
  only:
    - master

matrix:
  include:
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - CXX=clang++-8

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - lcov
      env:
        - CXX=g++-5

script: 
  - ./build.sh  

after_success:
  - |
    # Create coverage reporting (gcc only)
    if [ "$TRAVIS_COMPILER" == "gcc" ]; then
      cd ${TRAVIS_BUILD_DIR}
      lcov --version
      lcov --capture --directory . --output-file coverage.info
      #lcov --remove coverage.info $PWD'/gtest/*' '/usr/*' "${HOME}" --output-file coverage.info
      lcov --remove coverage.info $PWD'/gtest/*' '/usr/*' --output-file coverage.info
      lcov --list coverage.info
      # Uploading report to Codecov
      bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
    fi

notifications:
  email: false