image:
  - Visual Studio 2019
clone_folder: C:\projects

environment:
  PYTHON: "C:\\Python38-x64\\python.exe"

# Custom build script
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Python38\Scripts
  - cmd: "%PYTHON%" -m pip install --user conan
  - cmd: cmake -G "Visual Studio 16 2019" -A x64 -DCMAKE_BUILD_TYPE=Release ..
  - cmd: cmake --build . --config Release

# Custom test script
test_script:
  - cmd: ctest -C Release -VV

artifacts:
  - path: 'build\bin\intro.exe'
    name: cpp_starter_project
