version: 1.0.{build}
os: Visual Studio 2019

environment:
  matrix:
  - ARCH: x64

# Build worker image (VM template)
image:
- Visual Studio 2019

# Clone directory
clone_folder: c:\projects\source

install:
- set ORIGIN_PATH=%cd%
- set PATH=%PATH%;c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
- cd ..
- git clone https://github.com/google/googletest.git
- cd googletest
- cmake -G "Visual Studio 16 2019" .
- devenv googletest\gtest.sln /Upgrade
- devenv googletest\gtest.sln /Build
#- mkdir googletest\lib
#- copy googletest\gtest\Debug\gtestd.lib googletest\lib\gtest.lib
#- copy googletest\gtest\Debug\gtest_main-mdd.lib googletest\lib\gtest_main.lib
#- set GTEST_ROOT=%cd%\googletest
- set GTEST_ROOT=%cd%
- cd %ORIGIN_PATH%

# Custom build script
build_script:
- mkdir build
- cd build
- cmake c:\projects\source -G "Visual Studio 16 2019"
- cmake --build . --config "Debug"

# Custom test script
test_script:
- ctest -C Debug -VV