version: 1.0.{build}

# Build worker image (VM template)
image:
- Visual Studio 2019

environment:
  PYTHON: "C:\\Python37"

  matrix:
  # Conan development
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PYVER: py38
    TOXENV: py38-conandev
    CMAKE_GENERATOR: "Visual Studio 16 2019"  

# Clone directory
clone_folder: c:\projects\source

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - python -m pip install --upgrade pip
  - pip install tox==3.7.0 tox-venv==0.3.1

# Custom build script
build_script:
  - mkdir build
  - cd build
  - cmake c:\projects\source -G "Visual Studio 16 2019"
  - cmake --build . --config "Release"

# Custom test script
test_script:
  - ctest -C Release -VV

artifacts:
  - path: 'build\src\Release\intro.exe'
    name: cpp_starter_project
