image:
  - Visual Studio 2017
clone_folder: c:\projects\source
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake c:\projects\source -G "Visual Studio 15"
  - cmd: cmake --build . --config "Debug"
test_script:
  - cmd: ctest -C Debug
  
