version: 1.0.{build}
os: Visual Studio 2019

environment:
  matrix:
  - ARCH: x64

# Build worker image (VM template)
image:
- Visual Studio 2019

# Clone directory
clone_folder: c:\projects\source

install:

# Custom build script
build_script:
- mkdir build
- cd build
- cmake c:\projects\source -G "Visual Studio 16 2019"
- cmake --build . --config "Debug"

# Custom test script
test_script:
- ctest -C Debug -VV

build:
  parallel: true
  verbosity: minimal

artifacts:
- path: '\src\intro'
  name: cpp_starter_project
