version: 1.0.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "64"

# Clone directory
#clone_folder: c:\projects\source

install:
  - cmd: set PATH=%PYTHON%;%PYTHON%/Scripts;%PATH%
  - cmd: python --version
  - cmd: python -m pip install -U pip
  - cmd: echo "Downloading conan..."
  - cmd: pip install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

# Custom build script
build_script:
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake ../ -G "Visual Studio 16 2019" -A x64
  - cmd: cmake --build . --config Release

# Custom test script
test_script:
  - cmd: ctest -C Release -VV

artifacts:
  - path: 'build\src\Release\intro.exe'
    name: cpp_starter_project
