version: 1.0.{build}
os: Visual Studio 2019

environment:
  matrix:
  - ARCH: x64

# Build worker image (VM template)
image:
- Visual Studio 2019

# Clone directory
clone_folder: c:\projects\source

install:
#- set ORIGIN_PATH=%cd%
- set PATH=%PATH%;c:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
- git clone https://github.com/google/googletest.git
- cd googletest
- cmake -G "Visual Studio 16 2019" .
- devenv googletest\gtest.sln /Upgrade /Build
- xcopy ".\lib" ".\googletest\lib" /hievry
- set GTEST_ROOT=%cd%\googletest
#- cd %ORIGIN_PATH%

# Custom build script
build_script:
- mkdir build
- cd build
- cmake c:\projects\source -G "Visual Studio 16 2019"
- cmake --build . --config "Debug"

# Custom test script
test_script:
- ctest -C Debug -VV