version: 1.0.{build}

# Build worker image (VM template)
#image:
#  - Visual Studio 2019

#platform:
#  - x64

environment:
  matrix:
    # Windows w/64 bit Geo & python 3.6
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "3.6"
#      PYTHON: "C:\\Python36-x64"
#      PYTHON_ARCH: "64"  

stack:
  - python %PYTHON%

# Clone directory
clone_folder: c:\projects\source

install:
  - cmd: echo "Downloading conan..."
  - cmd: set PATH=%PATH%;%PYTHON%/Scripts/
  - cmd: pip.exe install conan
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

# Custom build script
build_script:
  - cmd: mkdir build
#  - cmd: conan install .
  - cmd: cd build
  - cmd: cmake ../ -DBUILD_TEST=TRUE  -G "Visual Studio 16 2019" -A x64
#  - cmake c:\projects\source -G "Visual Studio 16 2019" -A x64
  - cmd: cmake --build . --config Release  

# Custom test script
test_script:
  - cmd: ctest -C Release -VV

artifacts:
  - path: 'build\src\Release\intro.exe'
    name: cpp_starter_project
